// Re-export types from mode
export type { Study, Segment, Segmentation, SegmentationsResponse } from 'mode-t-chaii/api';

// Local extension types
export type SegmentStatsType = {
  volume: number;
  diameter: number;
  affected_organs: string;
  volume_change?: number;
  diameter_change?: number;
  lession_classification: string;
  lession_type: string;
};

export const lesionClassificationLabels: Record<string, string> = {
  Target: 'Target',
  'Non-Target': 'Non-Target',
  'New Lesion': 'New Lesion',
  'Non-Measurable': 'Non-Measurable',
  'Unknown': 'Unknown',
};

// Core classifications that should always be visible
export const coreClassifications = ['Target', 'Non-Target', 'New Lesion'];

// Optional classifications that should only be visible if they exist in the segmentation
export const optionalClassifications = ['Non-Measurable', 'Unknown'];

export const lesionTypeLabels: Record<string, string> = {
  Mass: 'Mass',
  Lymph: 'Lymph Node',
  Other: 'Other',
};

export const affectedOrgansLabels: Record<string, string> = {
  spleen: 'Spleen',
  kidney_right: 'Right Kidney',
  kidney_left: 'Left Kidney',
  gallbladder: 'Gallbladder',
  liver: 'Liver',
  stomach: 'Stomach',
  pancreas: 'Pancreas',
  adrenal_gland_right: 'Right Suprarenal Gland',
  adrenal_gland_left: 'Left Suprarenal Gland',
  lung_upper_lobe_left: 'Superior Lobe of Left Lung',
  lung_lower_lobe_left: 'Inferior Lobe of Left Lung',
  lung_upper_lobe_right: 'Superior Lobe of Right Lung',
  lung_middle_lobe_right: 'Middle Lobe of Right Lung',
  lung_lower_lobe_right: 'Inferior Lobe of Right Lung',
  esophagus: 'Esophagus',
  trachea: 'Trachea',
  thyroid_gland: 'Thyroid Gland',
  small_bowel: 'Small Intestine',
  duodenum: 'Duodenum',
  colon: 'Colon',
  urinary_bladder: 'Urinary Bladder',
  prostate: 'Prostate',
  kidney_cyst_left: 'Left Kidney Cyst',
  kidney_cyst_right: 'Right Kidney Cyst',
  sacrum: 'Sacrum',
  vertebrae_S1: 'Vertebra S1',
  vertebrae_L5: 'Vertebra L5',
  vertebrae_L4: 'Vertebra L4',
  vertebrae_L3: 'Vertebra L3',
  vertebrae_L2: 'Vertebra L2',
  vertebrae_L1: 'Vertebra L1',
  vertebrae_T12: 'Vertebra T12',
  vertebrae_T11: 'Vertebra T11',
  vertebrae_T10: 'Vertebra T10',
  vertebrae_T9: 'Vertebra T9',
  vertebrae_T8: 'Vertebra T8',
  vertebrae_T7: 'Vertebra T7',
  vertebrae_T6: 'Vertebra T6',
  vertebrae_T5: 'Vertebra T5',
  vertebrae_T4: 'Vertebra T4',
  vertebrae_T3: 'Vertebra T3',
  vertebrae_T2: 'Vertebra T2',
  vertebrae_T1: 'Vertebra T1',
  vertebrae_C7: 'Vertebra C7',
  vertebrae_C6: 'Vertebra C6',
  vertebrae_C5: 'Vertebra C5',
  vertebrae_C4: 'Vertebra C4',
  vertebrae_C3: 'Vertebra C3',
  vertebrae_C2: 'Vertebra C2',
  vertebrae_C1: 'Vertebra C1',
  heart: 'Heart',
  aorta: 'Aorta',
  pulmonary_vein: 'Pulmonary Vein',
  brachiocephalic_trunk: 'Brachiocephalic Trunk',
  subclavian_artery_right: 'Right Subclavian Artery',
  subclavian_artery_left: 'Left Subclavian Artery',
  common_carotid_artery_right: 'Right Common Carotid Artery',
  common_carotid_artery_left: 'Left Common Carotid Artery',
  brachiocephalic_vein_left: 'Left Brachiocephalic Vein',
  brachiocephalic_vein_right: 'Right Brachiocephalic Vein',
  atrial_appendage_left: 'Left Atrial Appendage',
  superior_vena_cava: 'Superior Vena Cava',
  inferior_vena_cava: 'Inferior Vena Cava',
  portal_vein_and_splenic_vein: 'Hepatic Portal Vein',
  iliac_artery_left: 'Left Common Iliac Artery',
  iliac_artery_right: 'Right Common Iliac Artery',
  iliac_vena_left: 'Left Common Iliac Vein',
  iliac_vena_right: 'Right Common Iliac Vein',
  humerus_left: 'Left Humerus',
  humerus_right: 'Right Humerus',
  scapula_left: 'Left Scapula',
  scapula_right: 'Right Scapula',
  clavicula_left: 'Left Clavicle',
  clavicula_right: 'Right Clavicle',
  femur_left: 'Left Femur',
  femur_right: 'Right Femur',
  hip_left: 'Left Hip',
  hip_right: 'Right Hip',
  spinal_cord: 'Spinal Cord',
  gluteus_maximus_left: 'Left Gluteus Maximus',
  gluteus_maximus_right: 'Right Gluteus Maximus',
  gluteus_medius_left: 'Left Gluteus Medius',
  gluteus_medius_right: 'Right Gluteus Medius',
  gluteus_minimus_left: 'Left Gluteus Minimus',
  gluteus_minimus_right: 'Right Gluteus Minimus',
  autochthon_left: 'Left Autochthon',
  autochthon_right: 'Right Autochthon',
  iliopsoas_left: 'Left Iliopsoas',
  iliopsoas_right: 'Right Iliopsoas',
  brain: 'Brain',
  skull: 'Skull',
  rib_left_1: 'Left Rib 1',
  rib_left_2: 'Left Rib 2',
  rib_left_3: 'Left Rib 3',
  rib_left_4: 'Left Rib 4',
  rib_left_5: 'Left Rib 5',
  rib_left_6: 'Left Rib 6',
  rib_left_7: 'Left Rib 7',
  rib_left_8: 'Left Rib 8',
  rib_left_9: 'Left Rib 9',
  rib_left_10: 'Left Rib 10',
  rib_left_11: 'Left Rib 11',
  rib_left_12: 'Left Rib 12',
  rib_right_1: 'Right Rib 1',
  rib_right_2: 'Right Rib 2',
  rib_right_3: 'Right Rib 3',
  rib_right_4: 'Right Rib 4',
  rib_right_5: 'Right Rib 5',
  rib_right_6: 'Right Rib 6',
  rib_right_7: 'Right Rib 7',
  rib_right_8: 'Right Rib 8',
  rib_right_9: 'Right Rib 9',
  rib_right_10: 'Right Rib 10',
  rib_right_11: 'Right Rib 11',
  rib_right_12: 'Right Rib 12',
  sternum: 'Sternum',
  costal_cartilages: 'Costal Cartilages',

  // Missing labels:
  heart_myocardium: 'Heart',
  heart_atrium_left: 'Heart',
  heart_ventricle_left: 'Heart',
  heart_atrium_right: 'Heart',
  heart_ventricle_right: 'Heart',
  pulmonary_artery: 'Heart',
  unknown: 'Unknown',
};
